# Generated by Django 4.0.5 on 2022-06-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0008_login_registrtion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrtion',
            new_name='Registration',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='null', max_length=200, upload_to=''),
            preserve_default=False,
        ),
    ]
