# Generated by Django 4.0.5 on 2022-06-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0009_rename_registrtion_registration_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
