# Generated by Django 4.0.5 on 2022-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0010_alter_post_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
