# Generated by Django 4.0.5 on 2022-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0011_comment_delete_comments_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('re_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
