# Generated by Django 4.0.5 on 2022-06-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0013_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bloggerz.post'),
            preserve_default=False,
        ),
    ]
