# Generated by Django 4.0.5 on 2022-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0014_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
