# Generated by Django 4.0.5 on 2022-06-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0016_delete_login_rename_posts_comment_post_post_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bloggerz.post'),
        ),
    ]
