# Generated by Django 4.0.5 on 2022-06-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0018_alter_comment_post_alter_post_intro_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
