# Generated by Django 4.0.5 on 2022-07-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerz', '0022_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='e_mail',
        ),
    ]
